### ISSUE TITLE
nier's mot/animation rotate data is in local space or object space?

### ISSUE THREAD

**Issue by Vstural** [Kerilk/bayonetta_tools#10]
hi, im trying to impl plugin for blender, but looks weird?
thx for reply!!

**Comment by Kerilk** [comment]
I am not super familiar with the terminology, and just understood it to code the decoding plugin for Noesis. I would say local space. Rotation order is a bit strange but mode 5 should be used in Nier as far as I remember that is z, y, x. The code doing this in Noesis can be found here:
https://github.com/Kerilk/noesis_bayonetta_pc/blob/08fece413121eb8a8e3f482f31ae0b54f4a4fe73/bayonetta_pc/MotionBayo.h#L737-L823
