### ISSUE TITLE
Eerrors when using assimp dependent binaries on Windows

### ISSUE THREAD

**Issue by flopware** [Kerilk/bayonetta_tools#17]
**Issue**
Running `wmb_export_assimp.rb` with an Assimp library DLL on Windows will result in a large stack trace error being present upon the command finishing.

**Reproduction**
1. Build latest version of [assimp](https://github.com/assimp/assimp) src into Windows DLL
2. Define built DLL as ASSIMP_DLL in environment variable
3. Run `wmb_export_assimp.rb` with any flag or option aside from --help

**Platform**
- Windows 11 Pro 22621.2134
- Ruby 3.1
- Latest bayonetta_tools release
- Assimp.dll compiled from [assimp](https://github.com/assimp/assimp) src using VS 2019

**Log**
[log.txt](https://github.com/Kerilk/bayonetta_tools/files/12592949/log.txt)

**Comment by Kerilk** [comment]
Thank you so much for the great report. These should be fixed. In the updated assimp-ffi gem and in https://github.com/Kerilk/bayonetta_tools/commit/def0403d138849db3f3efde54034b905aa5cd144?
