### ISSUE TITLE
Support to Switch?

### ISSUE THREAD

**Issue by makc-ar** [Kerilk/bayonetta_tools#2]
Hi **Kerilk!** How about NSW version? Example font .BNTX https://www30.zippyshare.com/v/aSsWCzn8/file.html or .idd textures https://www30.zippyshare.com/v/tVAU52qq/file.html

**Comment by Kerilk** [comment]
I plan to take a look at it. But due to work related constraints it might take a long before I am able to. So don't hold your breath.

**Comment by Kerilk** [comment]
I added support for the Switch version of Bayonetta 2. BNTX files should be correctly extracted/repacked. I also figured out most of the subtitle format as you seem interested in translation, there are dedicated binary templates for mcd and mcq files that contain the subtitles.
