### ISSUE TITLE
Anarchy Reigns animation

### ISSUE THREAD

**Issue by redtankbai** [Kerilk/bayonetta_tools#6]
can open dat model with plugin, but has no animation loaded

also canno unpack dat file with unpack tool which works for other Platinum games

not sure if your plugin supported animation in this game?

thx!

**Comment by redtankbai** [comment]
and happy new year :)

**Comment by Kerilk** [comment]
Animations should be supported. I don't remember where they are stored though. I'll try to check where they might be later this evening.

As far as dat tools are concerned, the bayonetta_tools which are command line will work. Other tools usually don't support little endian files.

**Comment by Kerilk** [comment]
And happy new year :)

**Comment by redtankbai** [comment]
when pick "Anarchy Reigns X360 Model (*.dat)" in noesis and double click dat file in content list, it will open model directly, without assign animation dialog like other game, so have no idea how to pick different anim file

**Comment by Kerilk** [comment]
Maybe the animation is havoc based, like vanquish. I don't see another reason I would have deactivated it. I'll check tonight.

**Comment by Kerilk** [comment]
Animations are in havoc format, I just checked.

**Comment by Crimsondice** [comment]
hello Kerilk! thank you for this amazing plugin, my question is i was able to load in a Anarchy Reigns models but whenever i try to use the same method from bayonetta1 to load in animations it doesn't work unfortunately, is there a way to make them work "preview them" ?

**Comment by Kerilk** [comment]
Unfortunately I don't support the Havok animation format, so it won't work for this particular game.
