### ISSUE TITLE
Hi so when I use the command to import my model then this happened. Can you help me with this ?

### ISSUE THREAD

**Issue by Cereza2811** [Kerilk/bayonetta_tools#9]
![image](https://user-images.githubusercontent.com/94898480/144696701-2ab2a574-4284-4554-8748-1c31910acdf1.png)

**Comment by Kerilk** [comment]
In order to import textures the importer needs the wtb file in the same directory as the wmb file.

**Comment by Cereza2811** [comment]
Okay but when I entered gem update --user-install then this error pop up. My friend said that they didn't have that bug when they entered it. So is it because of my computer or something else ? And if so do you have a solution for it ? Cause I reinstalled Ubuntu and this still happen. Thank you so much.
![image](https://user-images.githubusercontent.com/94898480/144770641-447a483c-4e6b-41b6-bcef-0c2e8bb3ce2d.png)

**Comment by Kerilk** [comment]
Seems your missing some dependencies:
`sudo apt install libffi-dev`

**Comment by Cereza2811** [comment]
The fiddle one is fixed but new errors occured it seem.
![Screenshot (275)](https://user-images.githubusercontent.com/94898480/144942099-400be636-76de-47c9-9335-401092ea054b.png)
![Screenshot (276)](https://user-images.githubusercontent.com/94898480/144942104-b4851c90-aa1a-45d7-b744-e081c3fb8937.png)
![Screenshot (277)](https://user-images.githubusercontent.com/94898480/144942107-7d0ec75a-98d8-495b-9fe5-badcfce4aaa3.png)
![Screenshot (280)](https://user-images.githubusercontent.com/94898480/144942108-abb707f6-a047-4e55-bed8-75536c8d8a51.png)

**Comment by Kerilk** [comment]
Just don't update the gems, it is not really needed anyway.
You can specify the gems you want to update later by specifying the name of the gem at the end of the gem update command.
